name: vol
channels: [conda-forge, defaults]
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - statsmodels
  - arch
  - scikit-learn
  - xgboost
  - optuna
  - shap
  - plotly
  - pyarrow
  - duckdb
  - pyspark
  - ipykernel
  - jupyterlab
  - tqdm
  - black
  - ruff
  - nbstripout
  - matplotlib
  - plotly
  - seaborn
  - pip
  - pip:
      - yfinance
      - pandas-datareader
